import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import { boardGameFormSchema, type BoardGameFormData, type BoardGameWithLocation } from "@/lib/schemas";

function getSupabase() {
  const key = process.env["SUPABASE_PUBLISHABLE_KEY"]!;
  return createClient<Database>(process.env["SUPABASE_URL"]!, key, { auth: { persistSession: false, autoRefreshToken: false }, global: { fetch: (input, init) => { const h = new Headers(init?.headers); if (key.startsWith("sb_") && h.get("Authorization") === `Bearer ${key}`) h.delete("Authorization"); h.set("apikey", key); return fetch(input, { ...init, headers: h }); } } });
}
const gameWithLocationQuery = `id, name, category, shelf_id, min_players, max_players, duration_minutes, min_age, difficulty, notes, image_url, shelves:shelf_id (id, name, rooms:room_id (id, name))`;
function mapGameRow(row: any): BoardGameWithLocation { const shelf = Array.isArray(row.shelves) ? row.shelves[0] : row.shelves; return { id: row.id, name: row.name, category: row.category ?? null, shelfId: row.shelf_id, minPlayers: row.min_players, maxPlayers: row.max_players, durationMinutes: row.duration_minutes, minAge: row.min_age, difficulty: row.difficulty, notes: row.notes, imageUrl: row.image_url ?? null, shelf: shelf ? { id: shelf.id, name: shelf.name, room: shelf.rooms ? (Array.isArray(shelf.rooms) ? shelf.rooms[0] : shelf.rooms) : null } : null }; }
export const searchGames = createServerFn({ method: "GET" }).inputValidator((input: { query: string }) => input).handler(async ({ data }) => { const supabase = getSupabase(); const q = data.query.trim(); let dbQuery = supabase.from("board_games").select(gameWithLocationQuery).order("name", { ascending: true }); if (q.length > 0) dbQuery = dbQuery.ilike("name", `%${q}%`); const { data: rows, error } = await dbQuery; if (error) throw error; return (rows || []).map(mapGameRow); });
export const getGameById = createServerFn({ method: "GET" }).inputValidator((input: { id: string }) => input).handler(async ({ data }) => { const supabase = getSupabase(); const { data: rows, error } = await supabase.from("board_games").select(gameWithLocationQuery).eq("id", data.id).limit(1); if (error) throw error; if (!rows || rows.length === 0) return null; return mapGameRow(rows[0]); });
export const createGame = createServerFn({ method: "POST" }).inputValidator((input: BoardGameFormData) => boardGameFormSchema.parse(input)).handler(async ({ data }) => { const supabase = getSupabase(); const { data: row, error } = await supabase.from("board_games").insert({ name: data.name, category: data.category ?? null, shelf_id: data.shelfId, min_players: data.minPlayers ?? null, max_players: data.maxPlayers ?? null, duration_minutes: data.durationMinutes ?? null, min_age: data.minAge ?? null, difficulty: data.difficulty, notes: data.notes ?? null, image_url: data.imageUrl ?? null }).select(gameWithLocationQuery).single(); if (error) throw error; return mapGameRow(row); });
export const updateGame = createServerFn({ method: "POST" }).inputValidator((input: { id: string; data: BoardGameFormData }) => ({ id: input.id, data: boardGameFormSchema.parse(input.data) })).handler(async ({ data }) => { const supabase = getSupabase(); const { data: row, error } = await supabase.from("board_games").update({ name: data.data.name, category: data.data.category ?? null, shelf_id: data.data.shelfId, min_players: data.data.minPlayers ?? null, max_players: data.data.maxPlayers ?? null, duration_minutes: data.data.durationMinutes ?? null, min_age: data.data.minAge ?? null, difficulty: data.data.difficulty, notes: data.data.notes ?? null, image_url: data.data.imageUrl ?? null }).eq("id", data.id).select(gameWithLocationQuery).single(); if (error) throw error; return mapGameRow(row); });
export const deleteGame = createServerFn({ method: "POST" }).inputValidator((input: { id: string }) => input).handler(async ({ data }) => { const supabase = getSupabase(); const { error } = await supabase.from("board_games").delete().eq("id", data.id); if (error) throw error; return { ok: true }; });

const LEGACY_COLLECTION_URL = "https://teletype.in/@ramsesqh/Coleccion";
export type LegacyGame = { name: string; category: string; minPlayers: number | null; maxPlayers: number | null; durationMinutes: number | null; minAge: number | null; difficulty: "casual" | "medium" | "hard" | "expert" };
function decodeEntities(value: string) { return value.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&nbsp;/g, " "); }
function cleanText(value: string) { return decodeEntities(value.replace(/<[^>]*>/g, " ")).replace(/\s+/g, " ").trim(); }
function categoryDifficulty(category: string): LegacyGame["difficulty"] { const c = category.toLocaleLowerCase(); if (c.includes("estrategia abstracta")) return "medium"; if (c === "estrategia" || c.includes("temático")) return "hard"; if (c.includes("roles ocultos")) return "medium"; return "casual"; }
function averageMinutes(value: string) { const nums = [...value.matchAll(/\d+/g)].map((m) => Number(m[0])).filter(Number.isFinite); return nums.length ? (nums.length > 1 ? Math.round((nums[0] + nums[1]) / 2) : nums[0]) : null; }
function parseLegacyCollection(html: string): LegacyGame[] { const normalized = html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<(br|\/p|\/div|\/li|\/h[1-6]|\/section|\/article)[^>]*>/gi, "\n").replace(/<[^>]+>/g, " "); const lines = normalized.split(/\n+/).map(cleanText).filter(Boolean); const result: LegacyGame[] = []; for (let i = 0; i < lines.length - 2; i++) { const category = lines[i + 1], details = lines[i + 2]; if (!category || !details) continue; const parts = details.split("|").map((p) => p.trim()); const players = parts.find((p) => /^\d+(?:-\d+)?$/.test(p)); const age = parts.find((p) => /^\d+\+$/.test(p)); if (!players || !age) continue; const [minP, maxP] = players.split("-").map(Number); const minAge = Number(age.replace("+", "")); const name = lines[i].replace(/\s*~~\s*$/, "").trim(); if (!name || result.some((g) => g.name.toLocaleLowerCase() === name.toLocaleLowerCase())) continue; result.push({ name, category, minPlayers: minP || null, maxPlayers: maxP || minP || null, durationMinutes: averageMinutes(parts.find((p) => /\d/.test(p) && p !== players && p !== age) ?? ""), minAge: minAge || null, difficulty: categoryDifficulty(category) }); } return result; }
export const previewLegacyCollection = createServerFn({ method: "GET" }).handler(async () => { const response = await fetch(LEGACY_COLLECTION_URL, { headers: { "User-Agent": "Mozilla/5.0" } }); if (!response.ok) throw new Error(`No se pudo leer la colección antigua (${response.status}).`); const games = parseLegacyCollection(await response.text()); return { source: LEGACY_COLLECTION_URL, games, count: games.length }; });
export const importLegacyCollection = createServerFn({ method: "POST" }).inputValidator((input: { shelfId: string; games: LegacyGame[] }) => input).handler(async ({ data }) => { const supabase = getSupabase(); const { data: existing, error: existingError } = await supabase.from("board_games").select("name"); if (existingError) throw existingError; const existingNames = new Set((existing || []).map((g: any) => String(g.name).trim().toLocaleLowerCase())); const toInsert = data.games.filter((g) => !existingNames.has(g.name.trim().toLocaleLowerCase())).map((g) => ({ name: g.name, category: g.category, shelf_id: data.shelfId, min_players: g.minPlayers, max_players: g.maxPlayers, duration_minutes: g.durationMinutes, min_age: g.minAge, difficulty: g.difficulty, notes: null, image_url: null })); if (!toInsert.length) return { inserted: 0, skipped: data.games.length }; const { error } = await supabase.from("board_games").insert(toInsert); if (error) throw error; return { inserted: toInsert.length, skipped: data.games.length - toInsert.length }; });
