/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UbicacionesRouteImport } from './routes/ubicaciones'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoNuevoRouteImport } from './routes/catalogo.nuevo'
import { Route as CatalogoIdEditarRouteImport } from './routes/catalogo.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UbicacionesRoute = UbicacionesRouteImport.update({
  id: '/ubicaciones',
  path: '/ubicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoNuevoRoute = CatalogoNuevoRouteImport.update({
  id: '/catalogo/nuevo',
  path: '/catalogo/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIdEditarRoute = CatalogoIdEditarRouteImport.update({
  id: '/catalogo/$id/editar',
  path: '/catalogo/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ubicaciones': typeof UbicacionesRoute
  '/catalogo/nuevo': typeof CatalogoNuevoRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/catalogo/$id/editar': typeof CatalogoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ubicaciones': typeof UbicacionesRoute
  '/catalogo/nuevo': typeof CatalogoNuevoRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/catalogo/$id/editar': typeof CatalogoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ubicaciones': typeof UbicacionesRoute
  '/catalogo/nuevo': typeof CatalogoNuevoRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/catalogo/$id/editar': typeof CatalogoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ubicaciones'
    | '/catalogo/nuevo'
    | '/catalogo/'
    | '/catalogo/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ubicaciones'
    | '/catalogo/nuevo'
    | '/catalogo'
    | '/catalogo/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/ubicaciones'
    | '/catalogo/nuevo'
    | '/catalogo/'
    | '/catalogo/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UbicacionesRoute: typeof UbicacionesRoute
  CatalogoNuevoRoute: typeof CatalogoNuevoRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  CatalogoIdEditarRoute: typeof CatalogoIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubicaciones': {
      id: '/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/ubicaciones'
      preLoaderRoute: typeof UbicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/nuevo': {
      id: '/catalogo/nuevo'
      path: '/catalogo/nuevo'
      fullPath: '/catalogo/nuevo'
      preLoaderRoute: typeof CatalogoNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$id/editar': {
      id: '/catalogo/$id/editar'
      path: '/catalogo/$id/editar'
      fullPath: '/catalogo/$id/editar'
      preLoaderRoute: typeof CatalogoIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UbicacionesRoute: UbicacionesRoute,
  CatalogoNuevoRoute: CatalogoNuevoRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  CatalogoIdEditarRoute: CatalogoIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
